### ISSUE TITLE
Heat cube generation

### ISSUE THREAD

**Issue by Bera97** [FanglinBao/HADAR#12]
Hi Fanglin,

first of all thank you for this great project. I have a few questions.

1. Is the heat cube a standardised output of the FLIR A325sc thermal camera you used? If it is not, what steps did you have to make in order to construct the heat cube?
2. Did you try stereo depth or you only did mono depth using GCNDepth model? If you tried stereo depth did you use any neural network for improved disparity estimation and which one?

Thank you very much.

**Comment by FanglinBao** [comment]
Hi Bera97,

Thanks for your interest in our work.
1. The heat cubes in this HADAR database are mainly synthesized through Blender. Please check the readme file of the database as well as the Monte Carlo Path Tracing section in Methods of the HADAR paper for a broad description. None of the heat cubes is from FLIR A325sc. Scene11 was collected by a pushbroom hyperspectral imager.
2. For Scene11, the real-world experiment, we used GCNDepth since we only have one view. For Scenes1-10, we used DeepPruner (pre-trained on the SceneFlow dataset) for binocular stereovision, please check Fig.S19 in the Supple. Info. of the HADAR paper.

**Comment by Bera97** [comment]
Thank you very much for the information!
